# Generated by Django 4.1.3 on 2022-11-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=12)),
                ('img', models.ImageField(upload_to='')),
                ('short_description', models.CharField(max_length=50)),
                ('Aartical', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
