# Generated by Django 4.1.3 on 2022-11-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmark', to='add.blog')),
            ],
        ),
    ]
