# Generated by Django 4.1.3 on 2022-11-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0003_categorytype_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='longitude',
        ),
    ]
